#!/bin/sh
# sendftp <host> <user> <passwd> <file> <path>"

# sendftp <host> <user> <passwd> <file> <path>
sendftp()
{
   HOST=$1
   USER=$2
   PASS=$3
   FILE=$4
   
   ftp -in <<END_SCRIPT
   open $HOST 
   user $USER $PASS
   put $FILE
   quit
END_SCRIPT
}

while [ "${1+defined}" ]; do
    case "$1" in
      -h | --host)
        if [ "${2+defined}" ]; then
          host=$2
          shift
        else
          echo "Error: missing number of pages to test!"
          exit 0
        fi
        ;;
      -u | --user)
        if [ "${2+defined}" ]; then
          user=$2
          shift
        else
          echo "Error: User name required!"
          exit 0
        fi 
        ;;
      -p | --pass)
        if [ "${2+defined}" ]; then
          pass=$2
          shift
        else
          echo "Error: Password required!"
          exit 0
        fi  
        ;;
      -f | --file)
        if [ "${2+defined}" ]; then
          file=$2
          shift
        else
          echo "Error: File required!"
          exit 0
        fi   
        ;;
      -d | --dir)
        if [ "${2+defined}" ]; then
          dir=$2
          shift
        else
          echo "Error: Path dir required!"
          exit 0
        fi   
        ;;
      *)  # No more options
        echo "Error: Unknown option: $1" >&2
        echo "   ex: `basename $0` <host> <user> <passwd> <file>" >&2
        exit 1 ;;
    esac
    shift
done

sendftp $host $user $pass $file $dir

exit 0
