delete from TESTCASE_FUNC_MAP;
delete from TESTCASE;
delete from FUNC;

DROP SEQUENCE FUNC_SEQ;
CREATE SEQUENCE  "TC_PROFILER"."FUNC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  

select FID FROM FUNC WHERE SOURCE_FILE like '%~\testcases\hello_lexmark.pdf' AND FUNC_NAME='main';
select SEQ, TLOC, FUNC_NAME FROM TESTCASE_FUNC_MAP t JOIN FUNC f ON t.FID = f.FID order by t.SEQ;
