#!/bin/sh

# Initialize variables
outpath=tests
ret=1
run_test=1
pages=-1
config="test"
type="*"
dir="/pfv/.firmwaretestcebu/pdf/v1_2"
testdir="./tests"
regex="([0-9a-z]+)*"
hits=0

if [ -z "$1" ]; then
  module=v1_2
else
  module=$1
fi


# const char * program_name
# int exit_status
help ()
{
   echo "Test case document classifier and unit test automation tool.";
   echo "Input directory will be scanned and filtered based on the given key filter string.";

   echo " Usage: ";
   echo "   Normal:          $0 [options] <filePath/testcase";
   echo "";
   echo " Options:";
   echo "    -d, --dir";
   echo "        intput testcase directory.";
   echo "    -p, --pdls";
   echo "        pdls test directory path.";
   echo "    -t, --type";
   echo "        document type to filter.";
   echo "    -c, --conf";
   echo "        config name";
   echo "    -s, --search";
   echo "        input search keyword";
   echo "    -n, --pages";
   echo "        number of pages to test";
   echo "";
   exit 0
}

filter_file()
{
  file=$1
  search=$2
  contains=0
  data=`grep -rl  $search $file`
  if [ ${#data} -gt 0 ]; then
    contains=1
  fi
          
  #if grep -q $search "$file"; then
  #  contains=1
  #fi
  
  echo "filtering $file for $search, result is: $contains"
  if [ $contains -eq 1 ]; then
    hits=$((hits+1))
  fi
  
  return $contains
}

# Parameters:
# $1 - input file
runtest()
{
    f=$1
    filter=$2
    fname=`basename $f | cut -d'.' -f1`
    
    outlog=`echo "$f" | md5sum`
    [[ $outlog =~ $regex ]]
    outlog="${BASH_REMATCH[1]}.log"

    fullname=`basename $f`
    rm -f $fname.cksum
    mkdir -p $outpath/$conf
    logfile=$outpath/$conf/$fname.sh.log
    
    if [ -f "$testdir/$fullname" ]; then
       echo " -- $f found skipping tests!"
       return
    fi

    if [ ! -f $logfile ]; then
      START_TIME=$(date +%s)
      echo "[@startTime: $START_TIME]" >> $outlog
      $pdlsapp -e `pdls_sniff $f` -O checksum -o $testdir/$conf/$fname- $f &> $logfile
      END_TIME=$(date +%s)
      echo "[@endTime: $END_TIME]" >> $outlog
    fi
    
    # parse output log for keyword/tag      
    if [ -f "$logfile" ]; then
      if [ ${filter+defined} ]; then
        filter_file $logfile $filter    
        if [ $? -eq 1 ]; then
          echo "[tag with: $filter]" >> $outlog
        fi
      fi
    fi
}

getparam() 
{
  ret=1
  if [ "${1+defined}" ]; then
    ret="$1"
    return 1
  else
    echo "Error: missing argument!"
    return 0
  fi 
}

while [ "${1+defined}" ]; do
    case "$1" in
      -h | --help)
        help $0 0
        ;;
      -v | --verbose)
        verbose="verbose" 
        ;;
      -d | --dir)
        if [ "${2+defined}" ]; then
          dir="$2"
          shift
        else
          echo "Error: source testcase directory!"
          echo "e.g $0 -d /pfv/.firmwaretestcebu/pdf/v1_2"
          exit 0
        fi 
        ;;
      -p | --pdls)
        if [ "${2+defined}" ]; then
          pdlsapp="$2/pdls"
          shift
        else
          echo "Error: testdir test directory!"
          echo "e.g $0 -p /bonus/scratch/tanch/pdls/tests"
          exit 0
        fi 
        ;;
      -t | --type)
        if [ "${2+defined}" ]; then
          type="$2"
          shift
        else
          echo "Error: missing document type filter argument!"
          exit 0
        fi 
        ;;
      -s | --search)
        if [ "${2+defined}" ]; then
          input_filter="$2"
          shift
        else
          echo "Error: file search keyword missing!"
          exit 0
        fi
        ;; 
      -c | --conf)
        if [ "${2+defined}" ]; then
          conf="$2"
          shift
        else
          echo "Error: missing argument!"
          exit 0
        fi
        ;;
      -n | --pages)
        if [ "${2+defined}" ]; then
          pages="$2"
          shift
        else
          echo "Error: missing number of pages to test!"
          exit 0
        fi
        ;;
      --) # End of all options
        break ;;
      -*)
        echo "Error: Unknown option: $1" >&2
        exit 1 ;;
      *)  # No more options
        break ;;
    esac
    shift
done

SAVEIFS=$IFS

if [ ! "${pdlsapp+defined}" ]; then
   echo "ERROR: pdlsapp path (-p option) not specified!"
   exit 0
fi

if [ ! -x "$pdlsapp" ]; then
  echo "ERROR: invalid pdls binary (-p option)!"
  exit 0
fi

if [ ! "${input_filter+defined}" ]; then
  echo "ERROR: Filter not specified"
  exit 0
fi

IFS='|' read -ra filters <<< "$input_filter"

echo "directory: $dir"
echo "document type: $type"
echo "config: $testdir/$conf.config"
echo "pdls: $pdlsapp"

#mysql --host=10.194.15.187 --user=tanch --password=tanch tutorial_db << EOF
#insert into files (fname,floc) values('samplefile', 'http://www.site.com/'); << EOF
#quit << EOF

IFS=$(echo -en "\n\b")
mkdir -p $testdir/$conf

for f in `find $dir -type f -name "*.$type"` ; do
  outlog=`echo "$f" | md5sum`
  [[ $outlog =~ $regex ]]
  outlog="${BASH_REMATCH[1]}.log"
  if [ -f $outlog ]; then
     echo "duplicate file: $outlog" 
     exit 1
  fi
  echo "invoking = ./pdls -e `pdls_sniff $f` $f" > $outlog
 
  # step 1: lookup tag/keywork inside testcase file
  for i in "${filters[@]}"; do
    START_TIME=$(date +%s)
    echo "[@startTime: $START_TIME]" >> $outlog
    filter_file $f $i
      if [ $? -eq 1 ]; then
        echo "[tag with: $i]" >> $outlog
      #else 
      # step 2: run pdlsapp if keyword/tag is not found on testcase file!
      #  runtest $f $i
      fi
    done
    END_TIME=$(date +%s)
    echo "[@endTime: $END_TIME]" >> $outlog
    sendftp -h 10.194.15.187 -u chritan -p welcome1 -f $outlog
#  break  
done

echo "TOTAL HITS: $hits"

IFS=$SAVEIFS 
exit 0



