--------------------------------------------------------
--  File created - Friday-August-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TESTCASE_CHECKSUMS
--------------------------------------------------------

  CREATE TABLE "TANCH"."TESTCASE_CHECKSUMS" 
   (	"TGUID" VARCHAR2(32 BYTE), 
	"PID" NUMBER DEFAULT 1, 
	"CHECKSUMS" CLOB, 
	"MODIFIED_BY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_01" 
 LOB ("CHECKSUMS") STORE AS BASICFILE (
  TABLESPACE "TBS_PERM_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TANCH"."TESTCASE_CHECKSUMS"."PID" IS 'Platform ID';
--------------------------------------------------------
--  DDL for Index TESTCASE_CHECKSUMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANCH"."TESTCASE_CHECKSUMS_PK" ON "TANCH"."TESTCASE_CHECKSUMS" ("TGUID", "PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_01" ;
--------------------------------------------------------
--  DDL for Trigger CHECKSUM_HISTORY_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANCH"."CHECKSUM_HISTORY_TRIGGER" 
AFTER UPDATE OR DELETE OR INSERT ON TESTCASE_CHECKSUMS 
FOR EACH ROW
BEGIN
    IF inserting THEN
        MERGE INTO CHECKSUM_HISTORY using DUAL on (TGUID=:old.TGUID AND PID=:old.PID)
        WHEN NOT matched THEN
            INSERT (TGUID,PID,MODIFIED_BY,ACTION,UPDATE_DATE,CHECKSUMS) VALUES (:old.TGUID, :old.PID, :old.MODIFIED_BY, 'insert', SYSDATE, :old.CHECKSUMS)
        WHEN matched THEN 
            UPDATE SET CHECKSUMS=:old.CHECKSUMS,MODIFIED_BY=:old.MODIFIED_BY,ACTION='insert',UPDATE_DATE=SYSDATE;
    ELSIF updating THEN
        MERGE INTO CHECKSUM_HISTORY using DUAL on (TGUID=:old.TGUID AND PID=:old.PID)
        WHEN NOT matched THEN
            INSERT (TGUID,PID,MODIFIED_BY,ACTION,UPDATE_DATE,CHECKSUMS) VALUES (:old.TGUID, :old.PID, :old.MODIFIED_BY, 'update', SYSDATE, :old.CHECKSUMS)
        WHEN matched THEN 
            UPDATE SET CHECKSUMS=:old.CHECKSUMS,MODIFIED_BY=:old.MODIFIED_BY,ACTION='update',UPDATE_DATE=SYSDATE;
    ELSIF deleting THEN
        MERGE INTO CHECKSUM_HISTORY using DUAL on (TGUID=:old.TGUID AND PID=:old.PID)
        WHEN NOT matched THEN
            INSERT (TGUID,PID,MODIFIED_BY,ACTION,UPDATE_DATE,CHECKSUMS) VALUES (:old.TGUID, :old.PID, :old.MODIFIED_BY, 'delete', SYSDATE, :old.CHECKSUMS)
        WHEN matched THEN 
            UPDATE SET CHECKSUMS=:old.CHECKSUMS,MODIFIED_BY=:old.MODIFIED_BY,ACTION='delete',UPDATE_DATE=SYSDATE;
    END IF;
END; 


/
ALTER TRIGGER "TANCH"."CHECKSUM_HISTORY_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table TESTCASE_CHECKSUMS
--------------------------------------------------------

  ALTER TABLE "TANCH"."TESTCASE_CHECKSUMS" ADD CONSTRAINT "TESTCASE_CHECKSUMS_UK1" UNIQUE ("TGUID", "PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_01"  ENABLE;
  ALTER TABLE "TANCH"."TESTCASE_CHECKSUMS" MODIFY ("PID" NOT NULL ENABLE);
  ALTER TABLE "TANCH"."TESTCASE_CHECKSUMS" MODIFY ("CHECKSUMS" NOT NULL ENABLE);
  ALTER TABLE "TANCH"."TESTCASE_CHECKSUMS" MODIFY ("TGUID" NOT NULL ENABLE);
